#
#spring:
#  datasource:
#  url: jdbc:h2:mem:exam;DB_CLOSE_DELAY=-1
#  username: h2
#  password: h2
#  # H2database 驱动
#  driver-class-name: org.h2.Driver
#  schema: classpath:/sql/schema.sql
#
#  h2:
#    console:
#      settings:
#        # 允许外网访问
#        web-allow-others: true
#      # H2控制台地址
#      path: /h2-console
#      # 打开H2控制台
#      enabled: true
#
#    # JPA
#    jpa:
#      properties:
#        hibernate:
#          # 更新表（不存在会自动创建）
#          ddl-auto: update
#          # 打印sql语句
#          show_sql: true
#          # 格式化sql语句
#          format_sql: true
#配置数据库连接地址
spring.datasource.url: jdbc:h2:mem:exam
#配置数据库驱动
spring.datasource.driver-class-name: org.h2.Driver
#配置数据库用户名
spring.datasource.username: root
#配置数据库密码
spring.datasource.password: root
#配置能远程访问
spring.h2.console.settings.web-allow-others: true
#配置访问地址
spring.h2.console.path: /h2-console
#配置项目启动 h2就启动
spring.h2.console.enabled: true
#进行该配置后，每次启动程序，程序都会运行resources/db/schema.sql文件，对数据库的结构进行操作。
spring.datasource.schema: classpath:sql/schema.sql
#进行该配置后，每次启动程序，程序都会运行resources/db/data.sql文件，对数据库的数据操作。
#spring.datasource.data: classpath:sql/data.sql

mybatis:
  config-location: classpath:mybatis-configuration.xml